name: GH-Pages

on:
   push:
      branches [ master ]

job:
  build:
     runs-on: ubuntu-latest

     step:
       - uses: actions/checkout@v2
       - uses: subosito/flutter-action@v1
       - uses: bluefireteam/flutter-gh-page@v7
